### ISSUE TITLE
Corrupted files (re)saving TIFF images

### ISSUE THREAD

**Issue by aritgithub** [Moustikitos/tyf#11]
Simple operation of (re)saving TIFF image file

`i1 = Tyf.open( '/Users/xatx/Desktop/TEST.tiff' )`
`i1.save( '/Users/xatx/Desktop/TESTTyf.tiff' )`

produces a corrupted file.

**Comment by Moustikitos** [comment]
Hi, can i have TEST.TIFF file ? Thank you.

**Comment by aritgithub** [comment]
You can use any tiff image. I created one with GIMP and I also downloaded one from Internet with the same result.
My env:
Mac OS X 10.7
Python 2.7.13

**Comment by Moustikitos** [comment]
Please, send me your corrupted file. Maybe it is a platform issue (tyf works fine on linux and win).
