### ISSUE TITLE
XMP metadata

### ISSUE THREAD

**Issue by Airyzf** [Moustikitos/tyf#17]
How do I modify XMP-related metadata?

        'Xmp.MicrosoftPhoto.LensModel': 'test', 
        'Xmp.MicrosoftPhoto.CameraSerialNumber': 'CameraSerialNumber', 
        'Xmp.MicrosoftPhoto.DateAcquired': '20200606', 
        'Xmp.MicrosoftPhoto.FlashManufacturer': 'FlashManufacturer', 
        'Xmp.MicrosoftPhoto.FlashModel': 'FlashModel', # 闪光灯型号
        'Xmp.MicrosoftPhoto.LensManufacturer': 'LensManufacturer'

**Comment by Moustikitos** [comment]
Hi,

XMP metadata is encoded in tag #700:

```700:   ("XMP", [3], None, "XML packet containing XMP metadata"),```

I didn't dev something to decode or encode [XMP metadata](https://developer.adobe.com/xmp/docs/XMPSpecifications/), but if you manage to do so you can add them into your pic using `Tyf`.

**Comment by Moustikitos** [comment]
The xmp metadata are stored in the `Tyf` object under `xmp` attribute. It is a Python [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html) object. So you should be able to edit it and save it.

**Comment by robotyzf** [comment]
> The xmp metadata are stored in the `Tyf` object under `xmp` attribute. It is a Python [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html) object. So you should be able to edit it and save it.

Thank you for your reply. I can get the xmp data, but there is still no corresponding data in the picture after modification and saving.

**Comment by Airyzf** [comment]
> The xmp metadata are stored in the `Tyf` object under `xmp` attribute. It is a Python [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html) object. So you should be able to edit it and save it.

Thank you for your reply. I can get the xmp data, but there is still no corresponding data in the picture after modification and saving.

**Comment by Moustikitos** [comment]
Make sure you modify the `xmp` attribute in place. The `xmp` attribute is actualy a shortcut pointing into the `JpegFile` instance (which is a `list` object).

```python
>>> import Tyf
>>> im = Tyf.open("test/xmp-exif.jpg")
>>> list.__getitem__(im, 2)[-1] is im.xmp
True
>>> for e in im: print(e[1].__class__)
...
<class 'Tyf.TiffFile'>
<class 'bytes'>
<class 'xml.etree.ElementTree.Element'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
<class 'bytes'>
```

If you do something like : 
```python
>>> im.xmp = ...
```
You destroy the link.

**Comment by Moustikitos** [comment]
Consider this example:
```python
>>> im = Tyf.open("test/xmp-exif.jpg")        
>>> im.xmp[0].remove(im.xmp[0][0])
>>> im.save("test.jpg")        
>>> im2 = Tyf.open("test.jpg")
>>> im = Tyf.open("test/xmp-exif.jpg")    
>>> len(Tyf.xmp.tostring(im2.xmp).decode())   
23304
>>> len(Tyf.xmp.tostring(im.xmp).decode())  
24265
```

**Comment by Moustikitos** [comment]
Hey,

I just pushed an update into the repo. You can set microsoft XMP tag:
```python
>>> im = Tyf.open("test/xmp-exif.jpg")
>>> data = {
...     'LensModel': 'test', 
...     'CameraSerialNumber': 'CameraSerialNumber', 
...     'DateAcquired': '20200606',
...     'FlashManufacturer': 'FlashManufacturer',
...     'FlashModel': 'FlashModel', # 闪光灯型号
...     'LensManufacturer': 'LensManufacturer'
... }
>>> for k, v in data.items():
>>>     im.set_xmp(k, v, ns="http://ns.microsoft.com/photo/1.0")
>>> im.save("test.jpg")
```

You can install this version:
```bash
python -m pip install git+https://github.com/Moustikitos/tyf.git
```

**Comment by Airyzf** [comment]
Thank you very much for your guidance.

**Comment by Moustikitos** [comment]
👍 You're welcome !

**Comment by Airyzf** [comment]
![image](https://github.com/Moustikitos/tyf/assets/27176468/8fb0af82-6ec4-44ef-9b88-ff8320f7adf9)
![image](https://github.com/Moustikitos/tyf/assets/27176468/c3f76116-ef21-4501-8db6-54ccaea5cfd9)

It seems that xmp is none

**Comment by Moustikitos** [comment]
Yes, `xmp` attribute returns `None` if no xmp segment found in the JPEG file.

**Comment by Airyzf** [comment]
There is no xmp data in the picture, and setting xmp data prompts None. How should I set it?

**Comment by Moustikitos** [comment]
Ok, i'll manage something to create the segment.

You can try:
```python
>>> im._JpegFile__xmp_idx = 2
>>> list.insert(im, 2, (65505, Tyf.xmp.Element("{adobe:ns:meta/}xmpmeta")))
>>> Tyf.xmp.SubElement(im.xmp, "{" + Tyf.XmpNamespace["RDF"] + "}RDF")
```
Then you should be able to add the data.

**Comment by Airyzf** [comment]
![image](https://github.com/Moustikitos/tyf/assets/27176468/9c5b6fc7-617b-4cae-9e79-0db967421d20)
There is still an error.

**Comment by Moustikitos** [comment]
I updated the example above...

**Comment by Moustikitos** [comment]
I've pushed somme changes. You just have to use `set_xmp` and even if no xmp segment found it will create it to add the very first item. Tell me if it works so I can cleanly close this issue.

**Comment by Airyzf** [comment]
![image](https://github.com/Moustikitos/tyf/assets/27176468/42315bdd-37b8-4c58-bbcb-c95798d9afba)
Got an error when save image

**Comment by Moustikitos** [comment]
Try :
```
pythpn -m pip uinstall Tyf
python -m pip install git+https://github.com/Moustikitos/tyf.git
```
You don't need the custom code anymore. Only use `set_xmp` function

**Comment by Airyzf** [comment]
data = {
            'LensModel': 'test', 
            'CameraSerialNumber': 'CameraSerialNumber', 
            'DateAcquired': '20200606',
            'FlashManufacturer': 'FlashManufacturer',
            'FlashModel': 'FlashModel', # 闪光灯型号
            'LensManufacturer': 'LensManufacturer'
        }

Only the last attribute takes effect.

**Comment by Moustikitos** [comment]
Ok, redo the commands to upgrade Tyf, It should be okay now.

**Comment by Airyzf** [comment]
Great, set_xmp succeeded, but get_xmp couldn't get the data. Did self.xmp fail to load?

**Comment by Moustikitos** [comment]
Make sure to use the appropriate namespace.
```python
>>> im = Tyf.open("test/xmp-exif.jpg")
unknown tag 42036 type [7]: <IFD tag Undefined:'Samsung Galaxy S7 Rear Camera'> ignored
>>> list.pop(im, 2)
(65505, <Element '{adobe:ns:meta/}xmpmeta' at 0x00000261507D5030>)
>>> del im._JpegFile__xmp_ns
>>> im.xmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Toons\Github\tyf\Tyf\__init__.py", line 411, in xmp
    raise XmpDataNotFound("no XMP segment found")
Tyf.XmpDataNotFound: no XMP segment found
>>> im.set_xmp("Comment", "test")  # default namespace EXIF used
<Element '{http://ns.adobe.com/exif/1.0/}Comment' at 0x00000261507C3790>
>>> im.set_xmp("Comment", "test", ns="MICROSOFT")  # namespace MICROSOFT used
<Element '{http://ns.microsoft.com/photo/1.0}Comment' at 0x00000261507C3880>
>>> im.get_xmp("Comment", ns="MICROSOFT")     
<Element '{http://ns.microsoft.com/photo/1.0}Comment' at 0x00000261507C3880>
>>> im.get_xmp("Comment")      
<Element '{http://ns.adobe.com/exif/1.0/}Comment' at 0x00000261507C3790>
>>> im.get_xmp("Comment").text
'test'
```

**Comment by Airyzf** [comment]
Yes, the namespace problem, thank you very much.

**Comment by Moustikitos** [comment]
👍
